# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from tkinter import dialog
from PyQt5 import QtCore, QtGui, QtWidgets
import pm


class Ui_MainWindow(object):
	def setupMainUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(585, 505)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.pushButton = QtWidgets.QPushButton(self.centralwidget)
		#self.pushButton.setGeometry(QtCore.QRect(130, 190, 91, 41))
		self.pushButton.setObjectName("pushButton")
		self.pushButton.clicked.connect(self.dialog)
		MainWindow.setCentralWidget(self.centralwidget)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateMainUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateMainUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "PMPro"))
		self.pushButton.setText(_translate("MainWindow", "Add New Password"))

	def dialog(self):
		self.dialogWindow = QtWidgets.QDialog()
		self.dialog = Ui_Dialog()
		self.dialog.setupDialogUi(self.dialogWindow)
		self.dialogWindow.show()

class Ui_Dialog(object):
	def buttonClick(self,email,password,platform):
		filepath = pm.get_filepath()
		data = pm.prepare_input(email,platform,password)
		pm.write_data(data, filepath)
		self.textEdit.clear()
		self.textEdit_2.clear()
		self.textEdit_3.clear()

	def setupDialogUi(self, Dialog):
		Dialog.setObjectName("Dialog")
		Dialog.resize(400, 400)
		self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
		self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
		self.buttonBox.setObjectName("buttonBox")
		self.pushButton = QtWidgets.QPushButton("Add",Dialog, clicked = lambda: self.buttonClick(self.textEdit.text(), self.textEdit_2.text(), self.textEdit_3.text()))
		self.textEdit = QtWidgets.QLineEdit(Dialog)
		self.textEdit.setGeometry(QtCore.QRect(140, 50, 101, 31))
		self.textEdit.setObjectName("textEdit")
		self.textEdit_2 = QtWidgets.QLineEdit(Dialog)
		self.textEdit_2.setGeometry(QtCore.QRect(140, 90, 101, 31))
		self.textEdit_2.setObjectName("textEdit_2")
		self.textEdit_3 = QtWidgets.QLineEdit(Dialog)
		self.textEdit_3.setGeometry(QtCore.QRect(140, 130, 101, 31))
		self.textEdit_3.setObjectName("textEdit_3")
		self.label = QtWidgets.QLabel(Dialog)
		self.label.setGeometry(QtCore.QRect(60, 60, 47, 13))
		self.label.setObjectName("label")
		self.label_2 = QtWidgets.QLabel(Dialog)
		self.label_2.setGeometry(QtCore.QRect(60, 100, 47, 13))
		self.label_2.setObjectName("label_2")
		self.label_3 = QtWidgets.QLabel(Dialog)
		self.label_3.setGeometry(QtCore.QRect(60, 140, 47, 13))
		self.label_3.setObjectName("label_3")

		self.retranslateDialogUi(Dialog)
		self.buttonBox.accepted.connect(Dialog.accept)
		self.buttonBox.rejected.connect(Dialog.reject)
		QtCore.QMetaObject.connectSlotsByName(Dialog)


	

	def retranslateDialogUi(self, Dialog):
		_translate = QtCore.QCoreApplication.translate
		Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
		self.label.setText(_translate("Dialog", "Email:"))
		self.label_2.setText(_translate("Dialog", "Password:"))
		self.label_3.setText(_translate("Dialog", "Platform:"))



if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupMainUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
