# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from ast import Delete
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidget, QTableWidgetItem, QVBoxLayout, QHBoxLayout, QLineEdit, QTabWidget
from PyQt5.QtCore import QRect, QTimer
import pm

# PyQt Class for the Main Window
class Ui_MainWindow(object):
	def setupMainUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.setFixedSize(585, 505)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.inputDialogButton = QtWidgets.QPushButton(self.centralwidget)
		self.inputDialogButton.setObjectName("inputDialogButton")
		self.inputDialogButton.clicked.connect(self.dialog)
		self.inputDialogButton.move(0,5)
		self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
		self.refreshButton.clicked.connect(self.refresh)
		self.refreshButton.move(100,5)
		self.refreshButton.setObjectName("refreshButton")
		self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
		self.deleteButton.setObjectName("deleteButton")
		self.deleteButton.clicked.connect(self.delete)
		self.deleteButton.move(175,5)
		self.genNewKeyButton = QtWidgets.QPushButton(self.centralwidget)
		self.genNewKeyButton.setObjectName("genNewKeyButton")
		self.genNewKeyButton.clicked.connect(self.reset)
		self.genNewKeyButton.move(250,5)
		MainWindow.setCentralWidget(self.centralwidget)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.tableWidget = QTableWidget(self.centralwidget)
		self.tableWidget.setRowCount(pm.get_password_count(pm.get_filepath()))
		self.tableWidget.setGeometry(QRect(0,35,585,470))
		self.tableWidget.setColumnCount(3)
		table_header = self.tableWidget.horizontalHeader()
		table_header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)
		table_header.setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
		self.tableWidget.setHorizontalHeaderLabels(["Email","Platform","Password"])
		for x in range(pm.get_password_count(pm.get_filepath())):
			data = pm.get_data_from_index(pm.get_filepath(), x)
			dots = "•"*len(pm.decrypt_password(bytes(data['encrypted'],'UTF-8'),pm.read_ciph_key(pm.get_confpath())))
			self.tableWidget.setItem(x,0, QTableWidgetItem(data['email']))
			self.tableWidget.item(x,0).setFlags(QtCore.Qt.ItemIsEnabled)
			self.tableWidget.setItem(x,1, QTableWidgetItem(data['platform']))
			self.tableWidget.item(x,1).setFlags(QtCore.Qt.ItemIsEnabled)
			self.tableWidget.setItem(x,2, QTableWidgetItem(dots))
			self.tableWidget.item(x,2).setFlags(QtCore.Qt.ItemIsEnabled)
		self.tableWidget.itemClicked.connect(lambda: self.unhidePassword(self.tableWidget.currentColumn(),self.tableWidget.currentRow()))
		self.retranslateMainUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateMainUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "PMPro"))
		self.inputDialogButton.setText(_translate("MainWindow", "Add New Password"))
		self.refreshButton.setText(_translate("Main Window", "Refresh"))
		self.deleteButton.setText(_translate("Main Window", "Delete"))
		self.genNewKeyButton.setText(_translate("Main Window", "Regen Key"))

	def reset(self):
		pm.reset_cipher_key()
	def refresh(self):
		self.tableWidget.setRowCount(pm.get_password_count(pm.get_filepath()))
		for current_row in range(pm.get_password_count(pm.get_filepath())):
			data = pm.get_data_from_index(pm.get_filepath(), current_row)
			dots = "•"*len(pm.decrypt_password(bytes(data['encrypted'],'UTF-8'),pm.read_ciph_key(pm.get_confpath())))
			self.tableWidget.setItem(current_row,0, QTableWidgetItem(data['email']))
			self.tableWidget.item(current_row,0).setFlags(QtCore.Qt.ItemIsEnabled)
			self.tableWidget.setItem(current_row,1, QTableWidgetItem(data['platform']))
			self.tableWidget.item(current_row,1).setFlags(QtCore.Qt.ItemIsEnabled)
			self.tableWidget.setItem(current_row,2, QTableWidgetItem(dots))
			self.tableWidget.item(current_row,2).setFlags(QtCore.Qt.ItemIsEnabled)
	
	def delete(self):
		self.deleteWindow = QtWidgets.QDialog(None, QtCore.Qt.WindowSystemMenuHint | QtCore.Qt.WindowCloseButtonHint)
		self.delete = Ui_Delete_Dialog()
		self.delete.setupDeleteUi(self.deleteWindow)
		self.deleteWindow.show()

	
	# Function to open dialog window
	def dialog(self):
		self.dialogWindow = QtWidgets.QDialog(None, QtCore.Qt.WindowSystemMenuHint | QtCore.Qt.WindowCloseButtonHint )
		self.dialog = Ui_Dialog()
		self.dialog.setupDialogUi(self.dialogWindow)
		self.dialogWindow.show()

	# Function to rehide the password after the user clicked to show it, called by a QTimer singleShot signal
	def rehidePassword(self,clicked_row,clicked_col,pass_len):
		dots = "•"*pass_len
		self.tableWidget.setItem(clicked_row,clicked_col,QTableWidgetItem(dots))
		self.tableWidget.item(clicked_row,clicked_col).setFlags(QtCore.Qt.ItemIsEnabled)

	# If the clicked item is a password, decrypt the password and show it for 2000 miliseconds, then call the function to rehide the password
	def unhidePassword(self,clicked_col,clicked_row):
		if clicked_col == 2:
			decrypted_pass = pm.decrypt_password(pm.get_password_from_index(pm.get_filepath(),clicked_row),pm.read_ciph_key(pm.get_confpath()))
			self.tableWidget.setItem(clicked_row,clicked_col,QTableWidgetItem(decrypted_pass))
			self.tableWidget.item(clicked_row,clicked_col).setFlags(QtCore.Qt.ItemIsEnabled)
			QTimer.singleShot(2000, lambda : self.rehidePassword(clicked_row,clicked_col,len(decrypted_pass)))

# PyQt Dialog class
class Ui_Dialog(object):
	# Function to write the user data into the JSON file
	def buttonClick(self,email,password,platform):
		filepath = pm.get_filepath()
		data = pm.prepare_input(email,platform,password,pm.read_ciph_key(pm.get_confpath()))
		pm.write_data(data, filepath)
		self.textEdit.clear()
		self.textEdit_2.clear()
		self.textEdit_3.clear()

	def setupDialogUi(self, Dialog):
		Dialog.setObjectName("Dialog")
		Dialog.setFixedSize(400, 400)
		self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
		self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
		self.buttonBox.accepted.connect(lambda: self.buttonClick(self.textEdit.text(), self.textEdit_2.text(), self.textEdit_3.text()))
		self.buttonBox.setObjectName("buttonBox")
		self.textEdit = QtWidgets.QLineEdit(Dialog)
		self.textEdit.setGeometry(QtCore.QRect(140, 50, 101, 31))
		self.textEdit.setObjectName("textEdit")
		self.textEdit_2 = QtWidgets.QLineEdit(Dialog)
		self.textEdit_2.setGeometry(QtCore.QRect(140, 90, 101, 31))
		self.textEdit_2.setObjectName("textEdit_2")
		self.textEdit_3 = QtWidgets.QLineEdit(Dialog)
		self.textEdit_3.setGeometry(QtCore.QRect(140, 130, 101, 31))
		self.textEdit_3.setObjectName("textEdit_3")
		self.label = QtWidgets.QLabel(Dialog)
		self.label.setGeometry(QtCore.QRect(60, 60, 47, 13))
		self.label.setObjectName("label")
		self.label_2 = QtWidgets.QLabel(Dialog)
		self.label_2.setGeometry(QtCore.QRect(60, 100, 47, 13))
		self.label_2.setObjectName("label_2")
		self.label_3 = QtWidgets.QLabel(Dialog)
		self.label_3.setGeometry(QtCore.QRect(60, 140, 47, 13))
		self.label_3.setObjectName("label_3")
		self.retranslateDialogUi(Dialog)
		self.buttonBox.accepted.connect(Dialog.accept)
		self.buttonBox.rejected.connect(Dialog.reject)
		QtCore.QMetaObject.connectSlotsByName(Dialog)

	def retranslateDialogUi(self, Dialog):
		_translate = QtCore.QCoreApplication.translate
		Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
		self.label.setText(_translate("Dialog", "Email:"))
		self.label_2.setText(_translate("Dialog", "Password:"))
		self.label_3.setText(_translate("Dialog", "Platform:"))

class Ui_Delete_Dialog(object):
	def setupDeleteUi(self, Delete_Dialog):
		Delete_Dialog.setObjectName("Delete_Dialog")
		Delete_Dialog.resize(325, 100)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(Delete_Dialog.sizePolicy().hasHeightForWidth())
		Delete_Dialog.setSizePolicy(sizePolicy)
		Delete_Dialog.setAutoFillBackground(False)
		self.buttonBox = QtWidgets.QDialogButtonBox(Delete_Dialog)
		self.buttonBox.setGeometry(QtCore.QRect(88, 60, 150, 30))
		self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
		self.buttonBox.accepted.connect(lambda: self.delete(self.comboBox.currentText()))
		self.buttonBox.setCenterButtons(True)
		self.buttonBox.setObjectName("buttonBox")
		self.comboBox = QtWidgets.QComboBox(Delete_Dialog)
		self.comboBox.setGeometry(QtCore.QRect(180, 20, 51, 22))
		self.comboBox.setObjectName("comboBox")
		for combo_count in range(pm.get_password_count(pm.get_filepath())):
			self.comboBox.addItem(str(combo_count+1))
		self.label = QtWidgets.QLabel(Delete_Dialog)
		self.label.setGeometry(QtCore.QRect(20, 20, 161, 21))
		font = QtGui.QFont()
		font.setPointSize(10)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.retranslateDeleteUi(Delete_Dialog)
		self.buttonBox.accepted.connect(Delete_Dialog.accept)
		self.buttonBox.rejected.connect(Delete_Dialog.reject)
		QtCore.QMetaObject.connectSlotsByName(Delete_Dialog)

	def delete(self, item_index):
		item_index = int(item_index)
		item_index-=1
		pm.delete_password(pm.get_filepath(),item_index)
	def retranslateDeleteUi(self, Delete_Dialog):
		_translate = QtCore.QCoreApplication.translate
		Delete_Dialog.setWindowTitle(_translate("Delete_Dialog", "Delete Password"))
		self.label.setText(_translate("Delete_Dialog", "Select Password to Delete:"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupMainUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
